version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
	commands:
	  - sudo apt-get update
	  - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
	  - sudo apt-get install nodejs

  pre_build:
    commands:
      - echo Running tests
      - npm install
      - npm test

  build:
    commands:
      - echo Building for production
      - npm install --production
	  - npm start

artifacts:
  files:
    - "**/*"
  name: MyMegaApp-$(date +%Y-%m-%d) 
