version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - sudo yum update -y
      - sudo yum install nodejs -y

  pre_build:
    commands:
      - echo Running tests
      - npm install

  build:
    commands:
      - echo Building for production
      - npm start

artifacts:
  files:
    - "**/*"
  name: MyMegaApp-$(date +%Y-%m-%d) 
