version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo Running tests
      - npm install

  build:
    commands:
      - echo Building for production
      - rm -rf node_modules
      - npm install --production

artifacts:
  files:
    - "**/*"
  name: MyMegaApp-$(date +%Y-%m-%d) 
